version: "3.9"
# servicos que vamos precisar rodar
services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
  #nome do servico
  app:
    # executa o build no Dockerfile
    build: .
    container_name: rentx
    ports:
      - 3333:3333
    #pega as informacoes do workdir (.) e joga pra dentro do container
    volumes:
      - .:/usr/app
    links:
      - database_ignite
    depends_on:
      - database_ignite
#quando cria volume dentro do container tem que informar o mapeamento pra dentro do docker
volumes:
  pgdata:
    driver: local
